# nolint start
# Processed data:
#   - Transform Daily incidence in Weekly incidence
#   - Generate a notional level data frame (sum by state)
std_covidcast_signal <- function(signal, limit_date, vect_week_date) {

  if (signal == "confirmed_admissions_covid_1d") {
    source <- "hhs"
  } else {
    source <- "jhu-csse"
  }

  # Call API to generate gold standard data from COVIDCast
  df <- covidcast::covidcast_signal(data_source = source, signal = signal,
                                    geo_type = "state", end_day = limit_date,
                                    as_of = Sys.Date())
  df$week <- MMWRweek::MMWRweek(df$time_value)$MMWRweek
  df$year <- MMWRweek::MMWRweek(df$time_value)$MMWRyear
  if (!(grepl("cumulative", signal))) {
    ## See fast version of gs_week_process
    df_state <- dplyr::summarise(df,
                                 value = sum(.data[["value"]], na.rm = TRUE),
                                 .by = c("geo_value", "year", "week")) |>
      dplyr::mutate(time_value = MMWRweek::MMWRweek2Date(.data[["year"]],
                                                         .data[["week"]],
                                                         7)) |>
      dplyr::distinct()
  }
  df_state <- dplyr::filter(df, .data[["time_value"]] %in% vect_week_date) |>
    dplyr::select(tidyr::all_of(c("time_value", "geo_value","value")))
  df_us <- dplyr::summarise(df_state,
                            value = sum(.data[["value"]], na.rm = TRUE),
                            .by = c("time_value")) |>
    dplyr::mutate(geo_value = "us")
  df_tot <- dplyr::bind_rows(df_state, df_us)
  return(df_tot)
}


#' Pull Truth data from COVIDCast
#'
#' Download and returns data from COVIDcast package in a Scenario Modeling
#' Hub format, with the incidence and cumulative data for each state and
#' US national level by epiweek. **DEPRECATED**
#'
#' @param signals list of signals to download (should be one or multiple in
#' the default list)
#'
#' @return a list of dataframe, each dataframe named with the corresponding
#' covidcast signal except "hospitalization" instead of
#' "confirmed_admissions_covid_1d"
#'
#' @export
#'
#' @details
#' The function output a list of 5 data frame (one by target) of observed
#' data in in a Scenario Modeling Hub format. The data are used on the
#' Scenario Modeling Hub website and are regenerated by using the `covidcast`
#' R package. Please, look at
#' \url{https://cran.r-project.org/web/packages/covidcast/index.html}
#' for more information.
#'
#' * For the cumulative numbers: use the `confirmed_cumulative_num` and
#'   `deaths_cumulative_num` signals from `jhu-csse`. As the data are expressed
#'   per day and the Scenario Modeling Hub use cumulative data by epiweek, the
#'   last day of each epiweek is selected for each location and the values are
#'   added between all states to obtains the US level data.
#'
#' * For the incidence numbers: use the `confirmed_incidence_num` and
#'   `deaths_incidence_num` signals from `jhu-csse` and
#'   `confirmed_admissions_covid_1d` from `hhs`. As the data are expressed per
#'   day and the Scenario Modeling Hub use cumulative data by epiweek, the sum
#'   of the incidences is calculated by epiweek and by location, and the values
#'   are added between all states to obtains the US level data.
#'
#' **Source data:**
#'
#' For case/death data, we use:
#' * https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/jhu-csse.html
#' * Signals: `"deaths_cumulative_num"`, `"confirmed_cumulative_num"`,
#' `"confirmed_incidence_num"`, `"deaths_incidence_num"`
#'
#' For hospitalization data, we use:
#' * https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/hhs.html
#' * Signals: `"confirmed_admissions_covid_1d"`
#'
#' @examples
#' \dontrun{
#'  lst_df <- pull_gs_data()
#'  lst_df
#'  str(lst_df)
#' }
#'
#' @importFrom dplyr mutate select summarise distinct filter bind_rows
#' @importFrom tidyr all_of
#' @importFrom MMWRweek MMWRweek MMWRweek2Date
#' @importFrom covidcast covidcast_signal
# nolint end
pull_gs_data <- function(signals = c("deaths_cumulative_num",
                                     "confirmed_cumulative_num",
                                     "confirmed_incidence_num",
                                     "deaths_incidence_num",
                                     "confirmed_admissions_covid_1d")) {
  .Deprecated("pull_nhsn_data")
  # date prerequisite
  # Date limit for Gold Standard data (data included the last full epiweek):
  eweek <- MMWRweek::MMWRweek(Sys.Date())$MMWRweek
  eyear <- MMWRweek::MMWRweek(Sys.Date())$MMWRyear

  limit_date <- as.Date("2021-01-02") + (as.numeric(eweek) + 52 *
                                           (as.numeric(eyear) - 2021)) * 7
  if (limit_date > Sys.Date()) limit_date <- limit_date - 1

  vect_week_date <- as.Date("2020-01-04")
  while (max(vect_week_date) < limit_date) {
    j <- max(vect_week_date) + 7
    vect_week_date <- c(vect_week_date, j)
  }
  rm(j)
  # signals
  lst_df <- purrr::map(signals, std_covidcast_signal, limit_date,
                       vect_week_date) |>
    setNames(signals)
  return(lst_df)
}
